<?php

namespace AppBundle\Repository;

/**
 * MusicianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicianRepository extends \Doctrine\ORM\EntityRepository
{
}
